config/routes.rb
Rails.application.routes.draw do

    root 'home#welcome'

    resources :up_file_share_authorities
    resources :folder_share_authorities

    delete 'self_destroy_folder_authority', to: 'folder_share_authorities#self_destroy', as: :self_destroy_folder_authority
    delete 'self_destroy_up_file_authority', to: 'up_file_share_authorities#self_destroy', as: :self_destroy_up_file_authority

    resources :up_file_shortcuts do
        collection do
            get :clone
        end
        member do
            get 'get_move'
            post 'move'
        end
    end

    resources :up_files do
        member do
            get 'rename'
            get 'resume_upload'
            get 'check_exist'
        end
    end

    resources :folder_shortcuts, only: [:destroy] do
        collection do
            get :clone
        end
        member do
            get 'get_move'
            post 'move'            
        end
    end


    resources :folders do
        collection do
            get 'shared_with_me'
        end
        member do
            get 'rename'
            get 'refresh'
            get 'get_move'
            post 'move'
        end
    end

    resources :comments

    devise_for :users

    ################################ Api ##################################

    namespace :api do
        resources :tokens, only: [:create, :destroy]

        resources :up_file_share_authorities, only: [:index, :create, :update, :destroy]
        resources :folder_share_authorities, only: [:index, :create, :update, :destroy]

        resources :up_file_shortcuts, only: [:destroy] do
            collection do
                get :clone
            end
            member do
                get 'get_move'
                post 'move'
            end
        end

        resources :up_files, only: [:show, :update, :destroy]

        resources :folder_shortcuts, only: [:destroy] do
            collection do
                get :clone
            end
            member do
                get 'get_move'
                post 'move'
            end
        end

        resources :folders, only: [:index, :show, :create, :update, :destroy] do
            collection do
                get 'shared_with_me'
            end
            member do
                get 'get_move'
                post 'move'
            end
        end

        resources :comments, only: [:create]

        resources :chat_rooms, only: [:show]

    end

    ################################ Cable ##################################

    mount ActionCable.server => '/cable'
end

app/models/up_file_share_authority.rb
class UpFileShareAuthority < ApplicationRecord
    belongs_to :up_file
    belongs_to :user

    scope :of_up_file, -> (id) { where(up_file_id: id) }

    scope :directed, -> { where(direct_share: true ) }
    scope :un_directed, -> { where(direct_share: false ) }

    validates :direct_share, :up_file_id, :user_id, presence: true, allow_blank: true

    
end

app/controllers/api/up_file_share_authorities_controller.rb
class Api::UpFileShareAuthoritiesController < Api::ApiController
    before_action :set_up_file_share_authority, only: [:update, :destroy]

    # GET /up_file_share_authorities
    def index
        @up_file_share_authorities = UpFileShareAuthority.of_up_file(params[:id]).includes(:user)
        render json: @up_file_share_authorities
    end

    # POST /up_file_share_authorities
    def create
        @up_file_share_authority = UpFileShareAuthority.new(up_file_share_authority_params)
        @user = User.find_by(email: params[:user_email])
        if @user.nil?
            render status: 401, json: {message: 'Không có email này!'}
        else
            @up_file_share_authority.user = @user
            begin
                @up_file_share_authority.save
                render status: 200, json: {message: "Chia sẻ với #{@user.username}"}
            rescue ActiveRecord::ActiveRecordError
                render status: 401, json: {message: "Có lỗi xảy ra ?"}
            end
        end
    end

    # PATCH/PUT /up_file_share_authorities/1
    def update

        update_rights_for_item @up_file_share_authority
        if @up_file_share_authority.save
            render status: 200, json: {message: "Sửa quyền thành công"}
        else
            render status: 401, json: {message: "Sửa quyền không thành công"}
        end
    end

    # DELETE /up_file_share_authorities/1
    def destroy

        @up_file_id = @up_file_share_authority.up_file_id
        begin
            @up_file_share_authority.destroy
            delete_all_shortcuts_for_up_file(@up_file_id, current_user)
            render status: 200, json: {message: "Xóa chia sẻ thành công"}
        rescue ActiveRecord::ActiveRecordError
            render status: 401, json: {message: "Xóa chia sẻ không thành công"}
        end

    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_up_file_share_authority
        @up_file_share_authority = UpFileShareAuthority.find(params[:id])
    end

    def delete_all_shortcuts_for_up_file(up_file_id, user)
        UpFileShortcut.where(up_file_id: up_file_id,  folder_id: user.folder_ids).delete_all
    end

    def update_rights_for_item item
        if params.has_key?(:can_view)
            item.can_view = params[:can_view]
        elsif params.has_key?(:can_rename)
            item.can_rename = params[:can_rename]
        elsif params.has_key?(:can_move)
            item.can_move = params[:can_move]
        elsif params.has_key?(:can_destroy)
            item.can_destroy = params[:can_destroy]
        end
    end

    # Only allow a trusted parameter "white list" through.
    def up_file_share_authority_params
        params.permit(:up_file_id, :user_id, :can_view, :can_rename, :can_move, :can_destroy, :direct_share)
    end
end

app/controllers/up_file_share_authorities_controller.rb
class UpFileShareAuthoritiesController < ApplicationController
    before_action :set_up_file_share_authority, only: [:show, :edit]

    # GET /up_file_share_authorities
    def index
        respond_to do |format|
            format.js {                
                @up_file_share_authorities = UpFileShareAuthority.of_up_file(params[:id]).includes(:user)
                @up_file_id = params[:id]
            }
        end
    end

    # GET /up_file_share_authorities/1
    def show
    end

    # GET /up_file_share_authorities/new
    def new
        @up_file_share_authority = UpFileShareAuthority.new
    end

    # GET /up_file_share_authorities/1/edit
    def edit
    end

    # POST /up_file_share_authorities
    def create
        @up_file_share_authority = UpFileShareAuthority.new(up_file_share_authority_params)
         @up_file = UpFile.find(params[:up_file_share_authority][:up_file_id])
        @user = User.find_by(email: params[:user_email])
        if @user.nil?
            @remote_error = {error: 'Khong tim thay email nay.'}
        elsif @user == @up_file.uploader
	    @remote_error = { error: 'User nay chinh la nguoi tao file nay.' }
        else
            @up_file_share_authority.user = @user
            begin
                @up_file_share_authority.save
            rescue ActiveRecord::ActiveRecordError
	    @remote_error = { error: 'Da chia se voi nguoi nay roi.' }
            end            
        end       

       respond_to do |format|
                format.js {
                    @up_file_share_authorities = UpFileShareAuthority.of_up_file(@up_file_share_authority.up_file_id).includes(:user)
                }                
            end
    end

    # PATCH/PUT /up_file_share_authorities/1
    def update
        begin
            @up_file_share_authority = UpFileShareAuthority.find(params[:id])
        rescue ActiveRecord::ActiveRecordError
        end

        update_rights_for_item @up_file_share_authority
        if @up_file_share_authority.save
            respond_to do |format|
                format.js {
                    @up_file_share_authorities = UpFileShareAuthority.of_up_file(@up_file_share_authority.up_file_id).includes(:user)
                }
                format.html {
                    redirect_to @up_file_share_authority, notice: 'File share authority was successfully updated.'
                }
            end
        else
            respond_to do |format|
                format.js {
                    @up_file_share_authorities = UpFileShareAuthority.of_up_file(@up_file_share_authority.up_file_id).includes(:user)
                }
                format.html {
                    render :edit
                }
            end
        end
    end

    # DELETE /up_file_share_authorities/1
    def destroy
        begin
            @up_file_share_authority = UpFileShareAuthority.find(params[:id])
        rescue ActiveRecord::ActiveRecordError
        end

        @up_file_id = @up_file_share_authority.up_file_id
        begin
            @up_file_share_authority.destroy
            delete_all_shortcuts_for_up_file(@up_file_id, current_user)
            respond_to do |format|
                format.js {
                    @up_file_share_authorities = UpFileShareAuthority.of_up_file(@up_file_id).includes(:user)
                }
                format.html {
                    redirect_to up_file_share_authorities_url, notice: 'File share authority was successfully destroyed.'
                }
            end
        rescue ActiveRecord::ActiveRecordError
            respond_to do |format|
                format.js {
                    @up_file_share_authorities = UpFileShareAuthority.of_up_file(@up_file_id).includes(:user)
                }
                format.html {
                    redirect_to up_file_share_authorities_url, notice: 'File share authority was successfully destroyed.'
                }
            end
        end

    end

    # Khi 1 người tự xóa chia sẻ đó trong "share with me" page.
    def self_destroy
        # tìm file muốn dừng chia sẻ
        @up_file_id = params[:up_file_id]
        @up_file_share_authority = UpFileShareAuthority.find_by(up_file_id: @up_file_id, user: current_user)
        # xóa hết các shortcut tới folder này.
        begin
            @up_file_share_authority.destroy
            delete_all_shortcuts_for_up_file(@up_file_id, current_user)
            redirect_to shared_with_me_folders_path
        rescue ActiveRecord::ActiveRecordError
            redirect_to shared_with_me_folders_path
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_up_file_share_authority
        @up_file_share_authority = UpFileShareAuthority.find(params[:id])
    end

    def delete_all_shortcuts_for_up_file(up_file_id, user)
        UpFileShortcut.where(up_file_id: up_file_id,  folder_id: user.folder_ids).delete_all
    end

    def update_rights_for_item item
        if params.has_key?(:can_view)
            item.can_view = params[:can_view]
        elsif params.has_key?(:can_rename)
            item.can_rename = params[:can_rename]
        elsif params.has_key?(:can_move)
            item.can_move = params[:can_move]
        elsif params.has_key?(:can_destroy)
            item.can_destroy = params[:can_destroy]
        end
    end

    # Only allow a trusted parameter "white list" through.
    def up_file_share_authority_params
        params.require(:up_file_share_authority).permit(:up_file_id, :user_id, :can_view, :can_rename, :can_move, :can_destroy, :direct_share)
    end
end

app/helpers/up_file_share_authorities_helper.rb
module UpFileShareAuthoritiesHelper
end

app/views/up_file_share_authorities/_authorities_list.html.erb
<table class="ui celled structured table">
    <thead>
        <tr>
            <td rowspan="2">Username</td>
            <td rowspan="2">Email</td>
            <td colspan="3" class="center aligned">Quyền</td>
            <td rowspan="2">Trực tiếp ?</td>
            <td rowspan="2">Hủy</td>
        </tr>
        <tr>            
            <td>Đổi tên</td>
            <td>Di chuyển</td>
            <td>Xóa</td>
        </tr>
    </thead>
    <tbody>        
        <% authorities.each do |authority| %>
            <tr>
                <td><%= authority.user.username %></td>
                <td><%= authority.user.email %></td>
                <td class="ui center aligned">
                    <%= link_to aut_params(authority.can_rename?), up_file_share_authority_path(authority, can_rename: !authority.can_rename?), method: :put, remote: true, class: 'detect-ajax-error' %>
                </td>
                <td class="ui center aligned">
                    <%= link_to aut_params(authority.can_move?), up_file_share_authority_path(authority, can_move: !authority.can_move?), method: :put, remote: true, class: 'detect-ajax-error' %>
                </td>
                <td class="ui center aligned">
                    <%= link_to aut_params(authority.can_destroy?), up_file_share_authority_path(authority, can_destroy: !authority.can_destroy?), method: :put, remote: true, class: 'detect-ajax-error' %>
                </td>
                <td class="ui center aligned">
                    <div class="ui fitted disabled checkbox">
                        <input type="checkbox" <%= "checked=''" if authority.direct_share? %> disabled="disabled">
                        <label></label>
                    </div>
                </td>
                <td><%= link_to 'Xóa', authority, method: :delete, remote: true, data: { confirm: 'Bạn muốn hủy chia sẻ với người này ?' } %></td>                
            </tr>
        <% end %>
    </tbody>
</table>

app/views/up_file_share_authorities/_form.html.erb
<%= simple_form_for(@up_file_share_authority) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :up_file %>
    <%= f.association :user %>
    <%= f.input :can_create %>
    <%= f.input :can_view %>
    <%= f.input :can_update %>
    <%= f.input :can_destroy %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/up_file_share_authorities/_share_manager.html.erb
<%= simple_form_for UpFileShareAuthority.new, remote: true do |f| %>
    <%= f.input :up_file_id, as: :hidden, input_html: { value: @up_file_id } %>
    <%= f.input :direct_share, as: :hidden, input_html: {value: true} %>
    <div class="field">
        <%= label_tag 'Nhập email:' %>
        <%= text_field_tag :user_email %>
    </div>
    <%= submit_tag 'Nhập tên', class:"ui button" %>
<% end %>
<div class="ui horizontal divider">Danh sách chia sẻ</div>
<div id="up-file-share-authorities">
    <%= render 'authorities_list', authorities: @up_file_share_authorities %>
</div>

app/views/up_file_share_authorities/create.js.erb
<% unless @remote_error %>
    $('#up-file-share-authorities').empty().append("<%= j render 'authorities_list', authorities: @up_file_share_authorities %>")
<% else %>
    setToast('warning', "<%= @remote_error[:error].to_s %>");
<% end %>

app/views/up_file_share_authorities/destroy.js.erb
$('#up-file-share-authorities').empty().append("<%= j render 'authorities_list', authorities: @up_file_share_authorities %>")

app/views/up_file_share_authorities/edit.html.erb
<h1>Editing Up File Share Authority</h1>

<%= render 'form', up_file_share_authority: @up_file_share_authority %>

<%= link_to 'Show', @up_file_share_authority %> |
<%= link_to 'Back', up_file_share_authorities_path %>

app/views/up_file_share_authorities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Up File Share Authorities</h1>

<table>
  <thead>
    <tr>
      <th>Up file</th>
      <th>User</th>
      <th>Can create</th>
      <th>Can view</th>
      <th>Can update</th>
      <th>Can destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @up_file_share_authorities.each do |up_file_share_authority| %>
      <tr>
        <td><%= up_file_share_authority.up_file %></td>
        <td><%= up_file_share_authority.user %></td>
        <td><%= up_file_share_authority.can_create %></td>
        <td><%= up_file_share_authority.can_view %></td>
        <td><%= up_file_share_authority.can_update %></td>
        <td><%= up_file_share_authority.can_destroy %></td>
        <td><%= link_to 'Show', up_file_share_authority %></td>
        <td><%= link_to 'Edit', edit_up_file_share_authority_path(up_file_share_authority) %></td>
        <td><%= link_to 'Destroy', up_file_share_authority, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Up File Share Authority', new_up_file_share_authority_path %>

app/views/up_file_share_authorities/index.js.erb
$('.modal.share-manager .content').empty().append('<%= j render 'share_manager' %>');

$('.modal.share-manager').modal('show');

app/views/up_file_share_authorities/new.html.erb
<h1>New Up File Share Authority</h1>

<%= render 'form', up_file_share_authority: @up_file_share_authority %>

<%= link_to 'Back', up_file_share_authorities_path %>

app/views/up_file_share_authorities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Up file:</strong>
  <%= @up_file_share_authority.up_file %>
</p>

<p>
  <strong>User:</strong>
  <%= @up_file_share_authority.user %>
</p>

<p>
  <strong>Can create:</strong>
  <%= @up_file_share_authority.can_create %>
</p>

<p>
  <strong>Can view:</strong>
  <%= @up_file_share_authority.can_view %>
</p>

<p>
  <strong>Can update:</strong>
  <%= @up_file_share_authority.can_update %>
</p>

<p>
  <strong>Can destroy:</strong>
  <%= @up_file_share_authority.can_destroy %>
</p>

<%= link_to 'Edit', edit_up_file_share_authority_path(@up_file_share_authority) %> |
<%= link_to 'Back', up_file_share_authorities_path %>

app/views/up_file_share_authorities/update.js.erb
$('#up-file-share-authorities').empty().append("<%= j render 'authorities_list', authorities: @up_file_share_authorities %>")