config/routes.rb
Rails.application.routes.draw do

    root 'home#welcome'

    resources :up_file_share_authorities
    resources :folder_share_authorities

    delete 'self_destroy_folder_authority', to: 'folder_share_authorities#self_destroy', as: :self_destroy_folder_authority
    delete 'self_destroy_up_file_authority', to: 'up_file_share_authorities#self_destroy', as: :self_destroy_up_file_authority

    resources :up_file_shortcuts do
        collection do
            get :clone
        end
        member do
            get 'get_move'
            post 'move'
        end
    end

    resources :up_files do
        member do
            get 'rename'
            get 'resume_upload'
            get 'check_exist'
        end
    end

    resources :folder_shortcuts, only: [:destroy] do
        collection do
            get :clone
        end
        member do
            get 'get_move'
            post 'move'            
        end
    end


    resources :folders do
        collection do
            get 'shared_with_me'
        end
        member do
            get 'rename'
            get 'refresh'
            get 'get_move'
            post 'move'
        end
    end

    resources :comments

    devise_for :users

    ################################ Api ##################################

    namespace :api do
        resources :tokens, only: [:create, :destroy]

        resources :up_file_share_authorities, only: [:index, :create, :update, :destroy]
        resources :folder_share_authorities, only: [:index, :create, :update, :destroy]

        resources :up_file_shortcuts, only: [:destroy] do
            collection do
                get :clone
            end
            member do
                get 'get_move'
                post 'move'
            end
        end

        resources :up_files, only: [:show, :update, :destroy]

        resources :folder_shortcuts, only: [:destroy] do
            collection do
                get :clone
            end
            member do
                get 'get_move'
                post 'move'
            end
        end

        resources :folders, only: [:index, :show, :create, :update, :destroy] do
            collection do
                get 'shared_with_me'
            end
            member do
                get 'get_move'
                post 'move'
            end
        end

        resources :comments, only: [:create]

        resources :chat_rooms, only: [:show]

    end

    ################################ Cable ##################################

    mount ActionCable.server => '/cable'
end

app/models/up_file_shortcut.rb
class UpFileShortcut < ApplicationRecord
    belongs_to :up_file
    belongs_to :folder

    validates :up_file_id, presence: true
    validates :folder_id, presence: true

    scope :directed, -> { where(shortcut: false ) }
    scope :un_directed, -> { where(shortcut: true ) }

end

app/controllers/api/up_file_shortcuts_controller.rb
class Api::UpFileShortcutsController < Api::ApiController

    include ApplicationHelper

    before_action :set_up_file_shortcut, only: [:get_move, :move, :destroy]

    # GET /clone_up_file_shortcuts/1
    def clone
        @up_file_to_clone = UpFile.find(params[:up_file_id])
        @new_shortcut = UpFileShortcut.new(up_file: @up_file_to_clone,  folder: Folder.root_folder_of_user(current_user), shortcut: true)
        begin
            @new_shortcut.save
            render status: 200, json: {message: 'Tạo shortcut thành công!'}
        rescue ActiveRecord::ActiveRecordError
            render status: 401, json: {message: 'Tạo shortcut không thành công!'}
        end
    end

    def get_move
        @folders_tree = Folder.root_folder_of_user(current_user).subtree.arrange_serializable
        render json: @folders_tree
    end

    def move
        @up_file_shortcut.folder_id = params[:new_parent_id]
        if @up_file_shortcut.save
            render status: 200, json: {message: 'Di chuyển thành công!'}
        else
            render status: 401, json: {message: 'Di chuyển không thành công!'}
        end
    end

    # DELETE /up_file_shortcuts/1
    def destroy
        begin
            unless @up_file_shortcut.shortcut?
                @up_file_shortcut.up_file.destroy
            end
            @up_file_shortcut.destroy
            render status: 200, json: {message: 'Xóa shortcut thành công!'}
        rescue
            render status: 401, json: {message: 'Xóa shortcut không thành công!'}
        end

    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_up_file_shortcut
        @up_file_shortcut = UpFileShortcut.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def up_file_shortcut_params
        params.permit(:up_file_id, :folder_id)
    end

end

app/controllers/up_file_shortcuts_controller.rb
class UpFileShortcutsController < ApplicationController
    include ApplicationHelper
    
    before_action :set_up_file_shortcut, only: [:show, :edit, :update,  :get_move, :move, :destroy]

    # GET /up_file_shortcuts
    def index
        @up_file_shortcuts = UpFileShortcut.all
    end

    # GET /up_file_shortcuts/1
    def show
    end

    # GET /up_file_shortcuts/new
    def new
        @up_file_shortcut = UpFileShortcut.new
    end

    # GET /up_file_shortcuts/1/edit
    def edit
    end

    # POST /up_file_shortcuts
    def create
        @up_file_shortcut = UpFileShortcut.new(up_file_shortcut_params)

        if @up_file_shortcut.save
            redirect_to @up_file_shortcut, notice: 'Up file shortcut was successfully created.'
        else
            render :new
        end
    end

    # GET /clone_up_file_shortcuts/1
    def clone
        @up_file_to_clone = UpFile.find(params[:up_file_id])
        @new_shortcut = UpFileShortcut.new(up_file: @up_file_to_clone,  folder: Folder.root_folder_of_user(current_user), shortcut: true)
        begin
            @new_shortcut.save
            redirect_to shared_with_me_folders_path
            UpFilesCreateBroadcastJob.perform_later root_folder_of_user(current_user).id
        rescue ActiveRecord::ActiveRecordError
            redirect_to shared_with_me_folders_path
        end
    end

    def get_move
        @folders_tree = Folder.root_folder_of_user(current_user).subtree.arrange
    end

    def move
        @up_file_shortcut.folder_id = params[:new_parent_id]
        if @up_file_shortcut.save
            redirect_to current_folder
        else
            redirect_to current_folder
        end
    end

    # DELETE /up_file_shortcuts/1
    def destroy
        up_file_id = @up_file_shortcut.up_file.id
        unless @up_file_shortcut.shortcut?
            @up_file_shortcut.up_file.destroy
        end
        @up_file_shortcut.destroy
        UpFilesDestroyBroadcastJob.set(wait: 5.second).perform_later up_file_id
        redirect_to current_folder, notice: 'Đã xóa file.'        
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_up_file_shortcut
        @up_file_shortcut = UpFileShortcut.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def up_file_shortcut_params
        params.require(:up_file_shortcut).permit(:up_file_id, :folder_id)
    end
end

app/helpers/up_file_shortcuts_helper.rb
module UpFileShortcutsHelper
end

app/views/up_file_shortcuts/_form.html.erb
<%= simple_form_for(@up_file_shortcut) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :up_file %>
    <%= f.association :folder %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/up_file_shortcuts/_get_move.html.erb
<% def draw_tree(node) %>
<% node.each do |key, value| %>
    <div class="item">
        <i class="folder icon"></i>
        <div class="content">
            <div class="header">
                <%= link_to key.name, move_up_file_shortcut_path(id: @up_file_shortcut.id, new_parent_id: key.id), method: :post  %>
            </div>
            <div class="content">Lần chỉnh sửa cuối: <%= time_ago_in_words key.updated_at %></div>
        </div>
        <% if !value.nil? %>
            <div class="ui list">
                <% draw_tree(value) %>
            </div>
        <% end %>
    </div>
<% end %>
<% end %>
<%# ^ helper tag %>
<div class="ui list">
    <% draw_tree @folders_tree %>
</div>

app/views/up_file_shortcuts/edit.html.erb
<h1>Editing Up File Shortcut</h1>

<%= render 'form', up_file_shortcut: @up_file_shortcut %>

<%= link_to 'Show', @up_file_shortcut %> |
<%= link_to 'Back', up_file_shortcuts_path %>

app/views/up_file_shortcuts/get_move.js.erb
$('.modal.move .content').empty().append('<%= j render 'get_move', up_file_shortcut: @up_file_shortcut %>');

$('.modal.move').modal('show');

app/views/up_file_shortcuts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Up File Shortcuts</h1>

<table>
  <thead>
    <tr>
      <th>Up file</th>
      <th>Folder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @up_file_shortcuts.each do |up_file_shortcut| %>
      <tr>
        <td><%= up_file_shortcut.up_file %></td>
        <td><%= up_file_shortcut.folder %></td>
        <td><%= link_to 'Show', up_file_shortcut %></td>
        <td><%= link_to 'Edit', edit_up_file_shortcut_path(up_file_shortcut) %></td>
        <td><%= link_to 'Destroy', up_file_shortcut, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Up File Shortcut', new_up_file_shortcut_path %>

app/views/up_file_shortcuts/new.html.erb
<h1>New Up File Shortcut</h1>

<%= render 'form', up_file_shortcut: @up_file_shortcut %>

<%= link_to 'Back', up_file_shortcuts_path %>

app/views/up_file_shortcuts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Up file:</strong>
  <%= @up_file_shortcut.up_file %>
</p>

<p>
  <strong>Folder:</strong>
  <%= @up_file_shortcut.folder %>
</p>

<%= link_to 'Edit', edit_up_file_shortcut_path(@up_file_shortcut) %> |
<%= link_to 'Back', up_file_shortcuts_path %>