config/routes.rb
Rails.application.routes.draw do

    root 'home#welcome'

    resources :up_file_share_authorities
    resources :folder_share_authorities

    delete 'self_destroy_folder_authority', to: 'folder_share_authorities#self_destroy', as: :self_destroy_folder_authority
    delete 'self_destroy_up_file_authority', to: 'up_file_share_authorities#self_destroy', as: :self_destroy_up_file_authority

    resources :up_file_shortcuts do
        collection do
            get :clone
        end
        member do
            get 'get_move'
            post 'move'
        end
    end

    resources :up_files do
        member do
            get 'rename'
            get 'resume_upload'
            get 'check_exist'
        end
    end

    resources :folder_shortcuts, only: [:destroy] do
        collection do
            get :clone
        end
        member do
            get 'get_move'
            post 'move'            
        end
    end


    resources :folders do
        collection do
            get 'shared_with_me'
        end
        member do
            get 'rename'
            get 'refresh'
            get 'get_move'
            post 'move'
        end
    end

    resources :comments

    devise_for :users

    ################################ Api ##################################

    namespace :api do
        resources :tokens, only: [:create, :destroy]

        resources :up_file_share_authorities, only: [:index, :create, :update, :destroy]
        resources :folder_share_authorities, only: [:index, :create, :update, :destroy]

        resources :up_file_shortcuts, only: [:destroy] do
            collection do
                get :clone
            end
            member do
                get 'get_move'
                post 'move'
            end
        end

        resources :up_files, only: [:show, :update, :destroy]

        resources :folder_shortcuts, only: [:destroy] do
            collection do
                get :clone
            end
            member do
                get 'get_move'
                post 'move'
            end
        end

        resources :folders, only: [:index, :show, :create, :update, :destroy] do
            collection do
                get 'shared_with_me'
            end
            member do
                get 'get_move'
                post 'move'
            end
        end

        resources :comments, only: [:create]

        resources :chat_rooms, only: [:show]

    end

    ################################ Cable ##################################

    mount ActionCable.server => '/cable'
end

app/models/folder.rb
class Folder < ApplicationRecord

    has_ancestry

    belongs_to :creator, class_name: 'User'
    has_one :chat_room, as: :crmable, dependent: :destroy
        
    has_many :folder_share_authorities, dependent: :destroy
    has_many :shared_users, through: :folder_share_authorities, source: :user

    ####### Quản lý các file shortcut tới thư mục ###########
    ##  1 file có nhiều đường dẫn tới các folder, tuy nhiên chỉ có 1 đường dẫn là 'direct', còn lại là 'shortcut'

    has_many :up_file_shortcuts, dependent: :destroy
    has_many :up_files, through: :up_file_shortcuts

    ####### Shortcut relation ######################

    has_many :shortcut_relationships, foreign_key: :destination_id, class_name: 'FolderShortcut', dependent: :destroy
    has_many :destination_relationships, foreign_key: :shortcut_id, class_name: 'FolderShortcut', dependent: :destroy

    has_many :shortcuts, through: :shortcut_relationships, source: :shortcut
    has_many :destinations, through: :destination_relationships, source: :destination

    accepts_nested_attributes_for :shortcut_relationships, allow_destroy: true
    accepts_nested_attributes_for :destination_relationships, allow_destroy: true

    ################################################

    scope :root_folder_of_user, ->(user) { where(creator_id: user.id, ancestry: nil).first }

    scope :children_of, ->(folder) { folder.children }

    scope :shared_with, -> (user) { user.shared_folders.merge(FolderShareAuthority.directed) }

    before_create :create_chat_room

    ###################################################

    validates :name, presence: true

    ###################################################

    def create_chat_room
        self.build_chat_room
        true
    end

    def is_directed_shared_with user
        !FolderShareAuthority.directed.where(folder_id: self.id, user_id: user.id).empty?
    end

    def is_shared_with user
        shared_users.include? user
    end


end

app/controllers/api/folders_controller.rb
class Api::FoldersController < Api::ApiController

    include ApplicationHelper

    before_action :set_folder, only: [:show, :move, :update, :destroy]

    def index
        @folder = Folder.root_folder_of_user(current_user)
        render json: @folder
        #render json: @folder, include: '**'
    end

    def show
        render json: @folder
        #render json: @folder, include: [:shortcuts, up_files: :user, chat_room: [comments: :user]]
    end

    def create
        @folder = Folder.new(folder_params)
        @folder.creator = current_user
        if @folder.save
            render status: 200, json: {message: 'Tạo folder thành công!', folder: @folder}
        else
            render status: 401, json: {message: 'Tạo folder không thành công!'}
        end
    end

    def update

        if @folder.update(folder_params)
            render status: 200, json: {message: 'Sửa folder thành công!', folder: @folder}
        else
            render status: 401, json: {message: 'Sửa folder không thành công!'}
        end
    end

    def destroy
        begin
            # Khi xóa 1 folder:
            # - xóa hết các file trong cây con đó (directedshare == true).
            UpFile.joins(:up_file_shortcuts).where(up_file_shortcuts: {shortcut: false, folder_id: @folder.subtree_ids}).destroy_all
            # - xóa hết các file shortcut tới cây con của folder (các direct shorcut tự động bị xóa khi xóa file trong câu trên)  .
            UpFileShortcut.un_directed.where(folder_id:  @folder.subtree_ids).destroy_all
            # - các folder của cây con tự động bị xóa -> các shortcut của folder cũng tự động bị xóa.

            # - xóa folder
            @folder.destroy
            render status: 200, json: {message: 'Xóa folder thành công!'}
        rescue
            render status: 401, json: {message: 'Xóa folder không thành công!'}
        end

    end

    def get_move
        @folders_tree = Folder.root_folder_of_user(current_user).subtree.arrange_serializable
        render json: @folders_tree
    end

    def move
        @folder.parent_id = params[:new_parent_id]
        if @folder.save
            render status: 200, json: {message: 'Move folder thành công!'}
        else
            render status: 401, json: {message: 'Move folder không thành công!'}
        end
    end

    private

    def set_folder
        begin
            @folder = Folder.find(params[:id])
        rescue
            render status: 401, json: {message: 'Không có folder này!'}
        end
    end

    def folder_params
        params.permit(:name, :creator_id, :parent_id)
    end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController

    include ApplicationHelper
    include FoldersHelper

    before_action :set_folder, only: [:edit, :rename, :get_move, :move]
    before_action :authenticate_user!

    # GET /folders
    # GET /folders.json
    def index
        set_current_folder Folder.root_folder_of_user(current_user).id
        set_current_children
        set_new_items
        @chat_room = current_folder.chat_room
    end

    # GET /folders/1
    # GET /folders/1.json
    def show
        begin
            @folder = Folder.find(params[:id])
            set_current_folder params[:id]
            set_current_children
            set_new_items
            @chat_room = current_folder.chat_room
        rescue ActiveRecord::RecordNotFound
            flash[:warning] = 'Không tìm thấy folder. Quay về home.'
            redirect_to folders_path
        end
    end

    # GET /folders/new
    def new
        @folder = Folder.new
    end

    # GET /folders/1/edit
    def edit
    end

    # POST /folders
    # POST /folders.json
    def create
        @folder = current_folder.children.create folder_params
        respond_to do |format|
            format.js {
                if @folder.save
                    set_children_folders
                    set_children_shortcuts
                    FoldersCreateBroadcastJob.perform_later @folder.id, current_folder.id
                else
                    @remote_error = true
                end
            }
        end

    end

    # PATCH/PUT /folders/1
    # PATCH/PUT /folders/1.json
    def update
        respond_to do |format|
            format.js {
                begin
                    @folder = Folder.find(params[:id])
                    @folder.update(folder_params)
                    set_children_folders
                    set_children_shortcuts

                rescue ActiveRecord::RecordNotFound
                    set_children_folders
                    set_children_shortcuts
                    @remote_error = {error: 'RecordNotFound'}
                rescue
                    @remote_error = {error: 'generic'}
                end
            }
        end
    end

    # DELETE /folders/1
    # DELETE /folders/1.json
    def destroy
        respond_to do |format|
            format.js {
                begin
                    @folder = Folder.find(params[:id])
                    # Khi xóa 1 folder:
                    # - xóa hết các file trong cây con đó (directedshare == true).
                    UpFile.joins(:up_file_shortcuts).where(up_file_shortcuts: {shortcut: false, folder_id: @folder.subtree_ids}).destroy_all
                    # - xóa hết các file shortcut tới cây con của folder (các direct shorcut tự động bị xóa khi xóa file trong câu trên)  .
                    UpFileShortcut.un_directed.where(folder_id:  @folder.subtree_ids).destroy_all
                    # - các folder của cây con tự động bị xóa -> các shortcut của folder cũng tự động bị xóa.
                    # - xóa folder
                    deleted_folders = @folder.subtree_ids
                    @folder.destroy
                    # => load lại cây thư mục
                    set_children_folders
                    set_children_shortcuts
                    FoldersDestroyBroadcastJob.perform_later deleted_folders
                rescue ActiveRecord::RecordNotFound
                    set_children_folders
                    set_children_shortcuts
                    @remote_error = {error: 'RecordNotFound'}
                rescue
                    @remote_error = {error: 'generic'}
                end
            }
        end

    end

    def refresh
        respond_to do |format|
            format.js {
                if params.has_key?(:part)
                    if params[:part] == 'folder'
                        set_children_folders
                        set_children_shortcuts
                    elsif params[:part] == 'file'
                        set_children_up_file_shortcuts
                    end

                end
            }
        end
    end
    # GET /folders/shared_with_me
    def shared_with_me
        @folders = Folder.shared_with current_user
        @up_files = UpFile.shared_with current_user
    end

    # GET /folders/1/rename
    def rename
    end

    # GET /folders/1/move
    def get_move
        @folders_tree = Folder.root_folder_of_user(current_user).subtree.arrange
    end

    def move
        @folder.parent_id = params[:new_parent_id]
        respond_to do |format|
            format.js {
                if @folder.save
                    set_children_folders
                    set_children_shortcuts
                else
                    @remote_error = true
                end
            }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
        @folder = Folder.find(params[:id])
    end

    def set_new_items
        @new_folder = Folder.new
        @new_comment = Comment.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def folder_params
        params.require(:folder).permit(:name, :creator_id)
    end
end

app/helpers/folders_helper.rb
module FoldersHelper

    def set_current_children
        set_children_folders
        set_children_shortcuts
        set_children_up_file_shortcuts
    end

    def set_children_folders
        @folders = Folder.children_of current_folder
    end

    def set_children_shortcuts
        @folder_shortcuts = current_folder.shortcut_relationships.includes(:shortcut)
    end

    def set_children_up_file_shortcuts
        @up_file_shortcuts = current_folder.up_file_shortcuts.joins(:up_file).merge(UpFile.readied)
    end

end

app/views/folders/_folder_view.html.erb
<div class="hidden">
    <p id="current_folder"><%= @current_folder.id %></p>    
</div>
<div class="container-fluid padding-2-size">
    <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-2">
            <div class="ui fluid huge vertical menu">
                <%= link_to 'Thư mục của tôi', folders_path, class: 'active teal item'  %>
                <%= link_to 'Được chia sẻ', shared_with_me_folders_path, class: 'item'  %>
                <%# link_to 'Bài học chung', '#', class: 'item'  %>
            </div>
        </div>
        <div class="col-lg-7 col-md-7 col-sm-7">
            <div class="ui big breadcrumb">
                <%= render 'shared/ancestors_breadcrumb', folder: current_folder %>
            </div>
            <div class="ui horizontal divider">Folder</div>
            <div class="row list folders">
                <%= render 'folders_list', folders: @folders, folder_shortcuts: @folder_shortcuts %>
            </div>
            <div class="ui horizontal divider">UpFile</div>
            <div class="row list up_files">
                <%= render 'up_files/up_files_list', up_file_shortcuts: @up_file_shortcuts %>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3">
            <div class="affix chat-zone">
                <%= render current_folder.chat_room %>
            </div>
        </div>
    </div>
</div>
<div class="ui small modal new folder">
    <div class="header">Tạo folder</div>
    <div id="create-folder-form" class="content">
        <%= render 'new_folder_lite_form', folder: @new_folder %>
    </div>
</div>
<div class="ui small modal new up_file">
    <div class="header">Chọn file muốn tải lên.</div>
    <div id="upload-file-form" class="content">
        <%= render 'new_up_file_lite_form', up_file: @new_up_file %>
    </div>
</div>
<div class="ui small modal share-manager">
    <div class="header">Quản lý quyền chia sẻ</div>
    <div class="content">
    </div>
</div>
<div class="ui small modal rename">
    <div class="header">Đặt lại tên</div>
    <div class="content"></div>
</div>
<div class="ui small modal move">
    <div class="header">Di chuyển</div>
    <div class="content"></div>
</div>

app/views/folders/_folders_list.html.erb
<table class="ui selectable striped large table">
    <thead>
        <tr>
            <td>
                <div class="ui header">Tên</div>
            </td>
            <td>
                <div class="ui header">Người tạo</div>
            </td>
            <td>
                <div class="ui header">Chỉnh sửa lần cuối</div>
            </td>
            <td>...</td>
        </tr>
    </thead>
    <tbody>
        <%# -------------------------- RENDER CHILDRENS -------------------  %>
        <% folders.each do |folder| %>
            <tr>
                <td class="full-row-clickable" data-href="<%= folder_path(folder) %>">
                    <div class="hidden">
                        <p class="children_folder_id"><%= folder.id %></p>
                    </div>
                    <i class="ui folder icon"></i>
                    <%= folder.name %>
                </td>
                <td class="full-row-clickable" data-href="<%= folder_path(folder) %>">
                    <%= folder.creator.username %>
                </td>
                <td class="full-row-clickable" data-href="<%= folder_path(folder) %>">
                    <%= time_ago_in_words folder.updated_at %>
                </td>
                <td>
                    <div class="popupable">
                        <i class="icon setting outline"></i>
                    </div>
                    <div class="ui popup right center transition">
                        <div class="ui one column divided center aligned grid">
                            <div class="column">
                                <%= link_to rename_folder_path(folder), remote: true do %>
                                    <i class="icon big edit outline"></i>
                                    <p>Đổi tên</p>
                                <% end %>
                            </div>
                            <div class="column">
                                <%= link_to folder, method: :delete, remote: true, data: {confirm: 'Bạn chắc chắn muốn xóa folder này ?'} do %>
                                    <i class="icon big trash outline"></i>
                                    <p>Xóa folder</p>
                                <% end %>
                            </div>
                            <div class="column">
                                <%= link_to get_move_folder_path(folder), remote: true do %>
                                    <i class="icon big exchange outline"></i>
                                    <p>Di chuyển</p>
                                <% end %>
                            </div>
                            <div class="column">
                                <%= link_to folder_share_authorities_path(id: folder.id), remote: true do %>
                                    <i class="icon big slideshare outline"></i>
                                    <p>Chia sẻ</p>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        <% end %>
        <%# -------------------------- RENDER SHORTCUTS -------------------  %>
        <% folder_shortcuts.each do |shortcut_rela| %>
            <tr>
                <td class="full-row-clickable" data-href="<%= folder_path(shortcut_rela.shortcut) %>">
                    <i class="ui folder outline icon"></i>
                    <%= shortcut_rela.shortcut.name %>
                </td>
                <td class="full-row-clickable" data-href="<%= folder_path(shortcut_rela.shortcut) %>">
                    <%= shortcut_rela.shortcut.creator.username %>
                </td>
                <td class="full-row-clickable" data-href="<%= folder_path(shortcut_rela.shortcut) %>">
                    <%= time_ago_in_words shortcut_rela.shortcut.updated_at %>
                </td>
                <td>
                    <div class="popupable">
                        <i class="icon setting outline"></i>
                    </div>
                    <div class="ui popup right center transition">
                        <div class="ui one column divided center aligned grid">
                            <div class="column">
                                <%= link_to rename_folder_path(shortcut_rela.shortcut), remote: true do %>
                                    <i class="icon big edit outline"></i>
                                    <p>Đổi tên</p>
                                <% end %>
                            </div>
                            <div class="column">
                                <%= link_to shortcut_rela, method: :delete, remote: true, data: {confirm: 'Bạn muốn xóa folder này ?'} do %>
                                    <i class="icon big trash outline"></i>
                                    <p>Xóa folder</p>
                                <% end %>
                            </div>
                            <div class="column">
                                <%= link_to get_move_folder_shortcut_path(shortcut_rela), remote: true do %>
                                    <i class="icon big exchange outline"></i>
                                    <p>Di chuyển</p>
                                <% end %>
                            </div>
                            <div class="column">
                                <%= link_to folder_share_authorities_path(id: shortcut_rela.shortcut.id), remote: true do %>
                                    <i class="icon big slideshare outline"></i>
                                    <p>Chia sẻ</p>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/folders/_get_move.html.erb
<% def draw_tree(node) %>
<% node.each do |key, value| %>
    <% if key != @folder %>
        <div class="item">
            <i class="folder icon"></i>
            <div class="content">
                <div class="header">
                    <%= link_to key.name, move_folder_path(id: @folder.id, new_parent_id: key.id), method: :post, remote: true  %>
                </div>
                <div class="content">Lần chỉnh sửa cuối: <%= time_ago_in_words key.updated_at %></div>
            </div>
            <% if !value.nil? %>
                <div class="ui list">
                    <% draw_tree(value) %>
                </div>
            <% end %>
        </div>
    <% end %>
<% end %>
<% end %>
<%# ^ helper tag %>
<div class="ui list">
    <% draw_tree @folders_tree %>
</div>

app/views/folders/_new_folder_lite_form.html.erb
<%= simple_form_for folder, remote: true do |f| %>
    <%= f.input :name %>
    <%= f.input :creator_id, as: :hidden, input_html: { value: current_user.id } %>
    <div class="form-actions">
        <%= f.button :submit %>
    </div>
<% end %>

app/views/folders/_new_up_file_lite_form.html.erb
<%= form_for UpFile.new, url: up_files_path(folder_id: current_folder.id), html: { multipart: true } do |f| %>
    <%# -- hidden fields - uploader and folder info -- %>
    <%= f.hidden_field :uploader_id, value: current_user.id %>
    <%= f.hidden_field :temp_up_id, value: SecureRandom.base64 %>
    <%# -- upload file section -- %>
    <div class="row">
    	<div class="col-md-6">
    		<div id="dropzone" class="fade well">Tha file vao day.</div>
    	</div>
    	<div class="col-md-1">
    		<div class="ui header"> hoặc </div>
    	</div>
    	<div class="col-md-5">    	
            <%= f.file_field :link %>
    	</div>
    </div>    
    <br/>    
    
<% end %>
<script id="template-upload" type="text/x-tmpl">
    <%= render 'shared/small_items/upload_tracker' %>
</script>

<style type="text/css" media="screen">
    #dropzone {
        background: palegreen;
        width: 100%;
        height: 100px;
        line-height: 100px;
        text-align: center;
        font-weight: bold;
    }
    #dropzone.in {
        width: 600px;
        height: 200px;
        line-height: 200px;
        font-size: larger;
    }
    #dropzone.hover {
        background: lawngreen;
    }
    #dropzone.fade {
        -webkit-transition: all 0.3s ease-out;
        -moz-transition: all 0.3s ease-out;
        -ms-transition: all 0.3s ease-out;
        -o-transition: all 0.3s ease-out;
        transition: all 0.3s ease-out;
        opacity: 1;
    }
</style>

app/views/folders/destroy.js.erb
<% unless @remote_error %>
    $('.row.list.folders').empty().append("<%= j render 'folders_list', folders: @folders, folder_shortcuts: @folder_shortcuts %>");    
    dummyBindingPopup();
    setToast('success', 'Đã xóa folder.');
<% else %>
    <% case @remote_error[:error] %>
    <% when 'RecordNotFound' %>
    $('.row.list.folders').empty().append("<%= j render 'folders_list', folders: @folders, folder_shortcuts: @folder_shortcuts %>");    
            dummyBindingPopup();
            setToast('warning', 'Folder đã bị xóa trước đó.');
        <% when 'Generic' %>
    setToast('warning', 'Có lỗi khi xóa folder.');
    <% end %>
<% end %>

app/views/folders/edit.html.erb
<h1>Editing Folder</h1>

<%= render 'form', folder: @folder %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

app/views/folders/get_move.js.erb
$('.modal.move .content').empty().append('<%= j render 'get_move', folder: @folder %>');

$('.modal.move').modal('show');

app/views/folders/move.js.erb
<% unless @remote_error %>
    $('.modal.move').modal('hide');
    $('.row.list.folders').empty().append("<%= j render 'folders_list', folders: @folders, folder_shortcuts: @folder_shortcuts %>");    
    dummyBindingPopup();
    setToast('success', 'Đã di chuyển folder.');
<% else %>
    $('.modal.move').modal('hide');
    setToast('warning', 'Có lỗi khi di chuyển folder.');
<% end %>

app/views/folders/new.html.erb
<h1>New Folder</h1>

<%= render 'form', folder: @folder %>

<%= link_to 'Back', folders_path %>

app/views/folders/refresh.js.erb
$('.modal').modal('hide');
<% if params[:part] == 'folder' %>
    $('.row.list.folders').empty().append("<%= j render 'folders_list', folders: @folders, folder_shortcuts: @folder_shortcuts %>");
<% elsif params[:part] == 'file' %>
    $('.row.list.up_files').empty().append("<%= j render 'up_files/up_files_list', up_file_shortcuts: @up_file_shortcuts %>");    
<% end %>
dummyBindingPopup();

app/views/folders/rename.js.erb
$('.modal.rename .content').empty().append('<%= j render 'rename', folder: @folder %>');

$('.modal.rename').modal('show');

app/views/folders/show.html.erb
<div id="folder-view">
    <%= render 'folder_view' %>
</div>

app/views/folders/update.js.erb
$('.modal.rename').modal('hide');    
<% unless @remote_error %>
    $('.row.list.folders').empty().append("<%= j render 'folders_list', folders: @folders, folder_shortcuts: @folder_shortcuts %>");
    dummyBindingPopup();
    setToast('success', 'Đã đổi tên folder.');
<% else %>
    <% case @remote_error[:error] %>
    <% when 'RecordNotFound' %>
    $('.row.list.folders').empty().append("<%= j render 'folders_list', folders: @folders, folder_shortcuts: @folder_shortcuts %>");    
	dummyBindingPopup();
	setToast('warning', 'Folder đã bị xóa trước đó.');
    	<% when 'Generic' %>
    setToast('warning', 'Không đổi được tên.');
    <% end %>
<% end %>