config/routes.rb
Rails.application.routes.draw do

    root 'home#welcome'

    resources :up_file_share_authorities
    resources :folder_share_authorities

    delete 'self_destroy_folder_authority', to: 'folder_share_authorities#self_destroy', as: :self_destroy_folder_authority
    delete 'self_destroy_up_file_authority', to: 'up_file_share_authorities#self_destroy', as: :self_destroy_up_file_authority

    resources :up_file_shortcuts do
        collection do
            get :clone
        end
        member do
            get 'get_move'
            post 'move'
        end
    end

    resources :up_files do
        member do
            get 'rename'
            get 'resume_upload'
            get 'check_exist'
        end
    end

    resources :folder_shortcuts, only: [:destroy] do
        collection do
            get :clone
        end
        member do
            get 'get_move'
            post 'move'            
        end
    end


    resources :folders do
        collection do
            get 'shared_with_me'
        end
        member do
            get 'rename'
            get 'refresh'
            get 'get_move'
            post 'move'
        end
    end

    resources :comments

    devise_for :users

    ################################ Api ##################################

    namespace :api do
        resources :tokens, only: [:create, :destroy]

        resources :up_file_share_authorities, only: [:index, :create, :update, :destroy]
        resources :folder_share_authorities, only: [:index, :create, :update, :destroy]

        resources :up_file_shortcuts, only: [:destroy] do
            collection do
                get :clone
            end
            member do
                get 'get_move'
                post 'move'
            end
        end

        resources :up_files, only: [:show, :update, :destroy]

        resources :folder_shortcuts, only: [:destroy] do
            collection do
                get :clone
            end
            member do
                get 'get_move'
                post 'move'
            end
        end

        resources :folders, only: [:index, :show, :create, :update, :destroy] do
            collection do
                get 'shared_with_me'
            end
            member do
                get 'get_move'
                post 'move'
            end
        end

        resources :comments, only: [:create]

        resources :chat_rooms, only: [:show]

    end

    ################################ Cable ##################################

    mount ActionCable.server => '/cable'
end

app/models/up_file.rb
class UpFile < ApplicationRecord
    include Rails.application.routes.url_helpers

    mount_uploader :link, UpFileUploader
    
    belongs_to :uploader, class_name: 'User'
    has_one :chat_room, as: :crmable, dependent: :destroy

    has_many :up_file_share_authorities, dependent: :destroy
    has_many :shared_users, through: :up_file_share_authorities, source: :user

    ####### Quản lý các file shortcut tới thư mục ###########
    ##  1 file có nhiều đường dẫn tới các folder, tuy nhiên chỉ có 1 đường dẫn là 'direct', còn lại là 'shortcut'

    has_many :up_file_shortcuts, dependent: :destroy
    has_many :folders, through: :up_file_shortcuts
    
    ################################################

    scope :shared_with, -> (user) { user.shared_up_files.merge(UpFileShareAuthority.directed) }

    scope :readied, -> { where(status: 'ready') }
    ################################################

    before_create :create_chat_room
    before_create :update_link_attributes

    TYPES = %W(mp4 mp3 pdf)
    STATUS = %W(uploading ready copying deleted)
    
    def check_type type        
        
        if !self.file_type.nil?
            
            if (self.file_type.include?(type) && TYPES.include?(type))
                return true
            else
                return false
            end
        else
            return false
        end
    end

    def to_jq_upload(error=nil)
        {
            "name" => read_attribute(:file_name),
            "size" => read_attribute(:file_size),
            "url" => link.url,
            "delete_url" => Rails.application.routes.url_helpers.up_file_path(self),
            "delete_type" => "DELETE"
        }
    end



    def create_chat_room
        self.build_chat_room
        true
    end

    def update_link_attributes
        if link.present? && link_changed?
            self.file_type = link.file.content_type
            self.file_size = link.file.size
            self.file_name = File.basename(link.filename,'.*').titleize
        end
    end

    def file_type_s
        TYPES.each do |type|            
            if self.file_type.includes?(type)                
                return type
            end            
        end
    end

end

app/controllers/api/up_files_controller.rb
class Api::UpFilesController < Api::ApiController

    include ApplicationHelper

    before_action :set_up_file, only: [:show, :update, :destroy]

    # GET /up_files/1
    def show
        render json: @up_file#, include: '**'
    end

    # PATCH/PUT /up_files/1
    def update
        if @up_file.update(up_file_params)
            render status: 200, json: {message: 'Sửa tên thành công!', up_file: @up_file}
        else
            render status: 401, json: {message: 'Sửa tên không thành công!'}
        end
    end

    # DELETE /up_files/1
    def destroy
        begin
            @up_file.destroy
            render status: 200, json: {message: 'Xóa File thành công!'}
        rescue
            render status: 401, json: {message: 'Xóa File không thành công!'}
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_up_file
        @up_file = UpFile.find(params[:id])
    end

    def save_direct_shortcut_for_file up_file, folder_id
        shortcut = UpFileShortcut.new(up_file: up_file, folder_id: folder_id)
        shortcut.save
    end

    # Only allow a trusted parameter "white list" through.
    def up_file_params
        params.permit(:link, :file_name, :uploader_id, :temp_up_id, up_file_shortcuts_params: [:up_file_id, :folder_id])
    end

end

app/controllers/up_files_controller.rb
class UpFilesController < ApplicationController
    include ApplicationHelper
    include UpFilesHelper

    before_action :set_up_file, only: [:continue_upload, :edit, :rename, :update, :destroy]
    before_action :set_new_items, only: [:show]

    # GET /up_files
    def index
        @up_files = UpFile.all
    end

    # GET /up_files/1
    def show
        begin
            @up_file = UpFile.find(params[:id])
            @chat_room = @up_file.chat_room
        rescue ActiveRecord::RecordNotFound
            flash[:warning] = 'Không tìm thấy file. Quay về home.'
            redirect_to folder_path
        end
    end

    # GET /up_files/new
    def new
        @up_file = UpFile.new
    end

    # GET /up_files/1/edit
    def edit
    end

    # POST /up_files
    def create

        # File tạm được upload lên
        @temp_upfile = UpFile.new up_file_params

        content_range = request.headers['CONTENT-RANGE']

        if content_range.nil? #file nhỏ hơn 5MB, lưu ko phải tính :D
            @temp_upfile.status = 'ready'
            @temp_upfile.save
            save_direct_shortcut_for_file @temp_upfile, params[:folder_id]
            UpFilesCreateBroadcastJob.set(wait: 2.second).perform_later current_folder.id
            return
        end

        content_length = request.headers['CONTENT-LENGTH'].to_i

        begin_of_chunk = content_range[/\ (.*?)-/,1].to_i
        end_of_chunk = content_range[/-(.*?)\//,1].to_i
        total_chunk = content_range[/\/(\d+)/,1].to_i
        # "bytes 100-999999/1973660678" will return '100'

        if (begin_of_chunk == 0)                           # upload part đầu tiên
            @temp_upfile.status = 'uploading'
            @temp_upfile.save
            save_direct_shortcut_for_file @temp_upfile, params[:folder_id]
        else
            @up_file = UpFile.find_by(temp_up_id: @temp_upfile.temp_up_id)
            @up_file.file_size += content_length

            if (Rails.env.development?)
                #code for FTP server
                get_ftp_connection do |ftp|
                    full_path = ::File.dirname "#{ENV['ftp_folder']}/#{@up_file.link.path}"
                    base_name = File.basename(@up_file.link.to_s)
                    ftp.chdir(full_path)
                    ftp.getbinaryfile(base_name, base_name, 1024)
                    File.open(base_name, "ab") do |f|
                        f.write(up_file_params[:link].read)
                    end
                    ftp.putbinaryfile(base_name, base_name, 1024)
                    File.delete(base_name)
                end
            else
                # code for local test
                File.open(@up_file.link.path, "ab") do |f|
                    f.write(up_file_params[:link].read)
                end
            end

            if (end_of_chunk == total_chunk - 1)  # kết thúc
                @up_file.status = 'ready'
            end

            @up_file.save
            if @up_file.status == 'ready'
                UpFilesCreateBroadcastJob.perform_later current_folder.id
            end
        end
    end


    # PATCH/PUT /up_files/1
    def update
        if @up_file.update(up_file_params)
            redirect_to :back
        else
            render :edit
        end
    end

    # DELETE /up_files/1
    def destroy
        @up_file.destroy
        redirect_to current_folder, notice: 'UpFile was successfully destroyed.'
        #render :json => true
    end

    def rename

    end

    def resume_upload
        @up_file = UpFile.find_by(temp_up_id: params[:id])
        render json: { file: {size: @up_file.file_size} } and return
    end

    def check_exist
        respond_to do |format|
            format.json {
                begin
                    @up_file = UpFile.find(params[:id])
                    render json: true
                rescue
                    flash[:warning] = 'File không còn tồn tại.'
                    render json: false
                end
            }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_up_file
        @up_file = UpFile.find(params[:id])
    end

    def set_new_items
        @new_comment = Comment.new
    end

    def save_direct_shortcut_for_file up_file, folder_id
        shortcut = UpFileShortcut.new(up_file: up_file, folder_id: folder_id)
        shortcut.save
    end

    # Only allow a trusted parameter "white list" through.
    def up_file_params
        params.require(:up_file).permit(:link, :file_name, :uploader_id, :temp_up_id, up_file_shortcuts_params: [:up_file_id, :folder_id])
    end
end

app/helpers/up_files_helper.rb
module UpFilesHelper

    def get_ftp_connection
        ftp = ExFTP.new        
        ftp.connect(ENV['ftp_host'], ENV['ftp_port'])

        begin
            ftp.passive = ENV['ftp_passive']
            ftp.login(ENV['ftp_user'], ENV['ftp_passwd'])

            yield ftp
        ensure
            ftp.quit
        end
    end

end

app/views/up_files/_form.html.erb
<%= simple_form_for(@up_file) do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
        <%= f.input :link %>
        <%= f.input :name %>
        <%= f.association :folder %>
    </div>
    <div class="form-actions">
        <%= f.button :submit %>
    </div>
<% end %>

app/views/up_files/_get_move.html.erb
<% def draw_tree(node) %>
<% node.each do |key, value| %>
    <div class="item">
        <i class="folder icon"></i>
        <div class="content">
            <div class="header">
                <%= link_to key.name, move_up_file_path(id: @up_file.id, new_parent_id: key.id), method: :post  %>
            </div>
            <div class="content">Lần chỉnh sửa cuối: <%= time_ago_in_words key.updated_at %></div>
        </div>
        <% if !value.nil? %>
            <div class="ui list">
                <% draw_tree(value) %>
            </div>
        <% end %>
    </div>
<% end %>
<% end %>
<%# ^ helper tag %>
<div class="ui list">
    <% draw_tree @folders_tree %>
</div>

app/views/up_files/_rename.html.erb
<%= form_for up_file do |f| %>
    <div class="ui form">
        <div class="field">
            <label>Nhập tên mới cho file</label>
            <%= f.text_field :file_name, value: up_file.file_name %>
        </div>
        <%= f.submit class: 'ui blue button' %>
    </div>
<% end %>

app/views/up_files/_swm_up_files_list.html.erb
<table class="ui single line selectable striped large table">
    <thead>
        <tr>
            <td>
                <div class="ui header">Tên</div>
            </td>
            <td>
                <div class="ui header">Loại</div>
            </td>
            <td>
                <div class="ui header">Kích thước</div>
            </td>
            <td>
                <div class="ui header">Người tạo</div>
            </td>
            <td>
                <div class="ui header">Chỉnh sửa lần cuối</div>
            </td>
            <td>...</td>
        </tr>
    </thead>
    <tbody>
        <% up_files.each do |up_file| %>
            <tr>
                <td class="full-row-clickable" data-href="<%= up_file_path(up_file) %>">
                    <%= up_file.file_name %>
                </td>
                <td class="full-row-clickable" data-href="<%= up_file_path(up_file) %>">
                    <%= up_file.file_type %>
                </td>
                <td class="full-row-clickable" data-href="<%= up_file_path(up_file) %>">
                    <%= number_to_human_size up_file.file_size %>
                </td>
                <td class="full-row-clickable" data-href="<%= up_file_path(up_file) %>">
                    <%= up_file.uploader.username %>
                </td>
                <td class="full-row-clickable" data-href="<%= up_file_path(up_file) %>">
                    <%= time_ago_in_words up_file.updated_at %>
                </td>
                <td>
                    <div class="popupable">
                        <i class="icon setting outline"></i>
                    </div>
                    <div class="ui popup right center transition">
                        <div class="ui one column divided center aligned grid">
                            <div class="column">
                                <%= link_to rename_up_file_path(up_file), remote: true do %>
                                    <i class="icon big edit outline"></i>
                                    <p>Đổi tên</p>
                                <% end %>
                            </div>
                            <div class="column">
                                <%= link_to clone_up_file_shortcuts_path(up_file_id: up_file.id) do %>
                                    <i class="icon big copy outline"></i>
                                    <p>Tạo shortcut trong Drive</p>
                                <% end %>
                            </div>
                            <div class="column">
                                <%= link_to self_destroy_up_file_authority_path( up_file_id: up_file.id), method: :delete, data: {confirm: 'Bạn không muốn được chia sẻ file này nữa ?'} do %>
                                    <i class="icon big trash outline"></i>
                                    <p>Dừng nhận chia sẻ file này</p>
                                <% end %>
                            </div>
                            <div class="column">
                                <%= link_to up_file_share_authorities_path(id: up_file.id), remote: true do %>
                                    <i class="icon big slideshare outline"></i>
                                    <p>Chia sẻ</p>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/up_files/_up_files_list.html.erb
<table class="ui selectable striped large table">
    <thead>
        <tr>
            <td>
                <div class="ui header">Tên</div>
            </td>
            <td>
                <div class="ui header">Loại</div>
            </td>
            <td>
                <div class="ui header">Kích thước</div>
            </td>
            <td>
                <div class="ui header">Người tạo</div>
            </td>
            <td>
                <div class="ui header">Chỉnh sửa lần cuối</div>
            </td>
            <td>...</td>
        </tr>
    </thead>
    <tbody>
        <% up_file_shortcuts.each do |shortcut| %>
            <tr>
                <td class="full-row-clickable" data-href="<%= up_file_path(shortcut.up_file) %>">
                <div class="hidden">
                        <p class="children_up_file_id"><%= shortcut.up_file.id %></p>
                    </div>
                    <%= shortcut.up_file.file_name %>
                </td>
                <td class="full-row-clickable" data-href="<%= up_file_path(shortcut.up_file) %>">
                    <%= shortcut.up_file.file_type %>
                </td>
                <td class="full-row-clickable" data-href="<%= up_file_path(shortcut.up_file) %>">
                    <%= number_to_human_size shortcut.up_file.file_size %>
                </td>
                <td class="full-row-clickable" data-href="<%= up_file_path(shortcut.up_file) %>">
                    <%= shortcut.up_file.uploader.username %>
                </td>
                <td class="full-row-clickable" data-href="<%= up_file_path(shortcut.up_file) %>">
                    <%= time_ago_in_words shortcut.up_file.updated_at %>
                </td>
                <td>
                    <div class="popupable">
                        <i class="icon setting outline"></i>
                    </div>
                    <div class="ui popup right center transition">
                        <div class="ui one column divided center aligned grid">
                            <div class="column">
                                <%= link_to rename_up_file_path(shortcut.up_file), remote: true do %>
                                    <i class="icon big edit outline"></i>
                                    <p>Đổi tên</p>
                                <% end %>
                            </div>
                            <div class="column">
                                <%= link_to shortcut, method: :delete, data: {confirm: 'Bạn muốn xóa file này ?'} do %>
                                    <i class="icon big trash outline"></i>
                                    <p>Xóa file</p>
                                <% end %>
                            </div>
                            <div class="column">
                                <%= link_to get_move_up_file_shortcut_path(shortcut), remote: true do %>
                                    <i class="icon big exchange outline"></i>
                                    <p>Di chuyển</p>
                                <% end %>
                            </div>
                            <div class="column">
                                <%= link_to up_file_share_authorities_path(id: shortcut.up_file.id), remote: true do %>
                                    <i class="icon big slideshare outline"></i>
                                    <p>Chia sẻ</p>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/up_files/edit.html.erb
<h1>Editing UpFile</h1>
<%= render 'form', up_file: @up_file %>
<%= link_to 'Show', @up_file %> |
<%= link_to 'Back', up_files_path %>

app/views/up_files/index.html.erb
<p id="notice"><%= notice %></p>
<h1>UpFiles</h1>
<table>
    <thead>
        <tr>
            <th>Link</th>
            <th>Name</th>
            <th>Folder</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
        <% @up_files.each do |up_file| %>
            <tr>
                <td><%= up_file.link %></td>
                <td><%= up_file.name %></td>
                <td><%= up_file.folder %></td>
                <td><%= link_to 'Show', up_file %></td>
                <td><%= link_to 'Edit', edit_up_file_path(up_file) %></td>
                <td><%= link_to 'Destroy', up_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>
<br>
<%= link_to 'New UpFile', new_up_file_path %>

app/views/up_files/new.html.erb
<h1>New UpFile</h1>
<%= render 'form', up_file: @up_file %>
<%= link_to 'Back', up_files_path %>

app/views/up_files/rename.js.erb
$('.modal.rename .content').empty().append('<%= j render 'rename', up_file: @up_file %>');

$('.modal.rename').modal('show');

app/views/up_files/show.html.erb
<div class="hidden">
    <p id="current_file"><%= @up_file.id %></p>    
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-9 col-md-9 col-sm-9 up-file-box">
            <% if @up_file.check_type 'mp4' %>
                <div class="video-box">                    
                    <%= video_tag( @up_file.link , size: "620x440", controls: true, autoplay: true) %>
                </div>
            <% elsif @up_file.check_type 'mp3' %>
                <%= audio_tag( @up_file.link , controls: true, autoplay: true) %>
            <% elsif @up_file.check_type 'pdf' %>
                <div class="pdf-box">
                    <iframe src=<%= @up_file.link %> width="700" height="500" style="border: none;"> </iframe>
                </div>
            <% end %>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3">
            <div class="affix chat-zone">
                <%= render @up_file.chat_room %>
            </div>
        </div>
    </div>
</div>
<%# link_to 'Edit', edit_up_file_path(@up_file) %> |
<%# link_to 'Back', up_files_path %>